---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

params:
  ATTENDEE_SERVICE_URL: https://attendee-service-droitural-relaxedness.local.pcfdev.io

inputs:
- name: attendee-service

run:
  path: attendee-service/ci/tasks/smoke-test.sh