---
resources:
- name: attendee-service
  type: git
  source:
    uri: https://github.com/vladimirnalitkin/pcf-attendee-service-code.git  #<----- REPLACE ME
    branch: test

- name: deploy-attendee-service
  type: cf
  source:
    api: api.local.pcfdev.io        #<----- REPLACE ME
    username: ci
    password: pass
    organization: p-spring-cloud-services    #<----- REPLACE ME
    space: instances         #<----- REPLACE ME
    skip_cert_check: true

jobs:
- name: test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
  - task: test
    file: attendee-service-source/ci/tasks/test.yml

- name: deploy
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [test]
  - task: package
    file: attendee-service-source/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service/manifest.yml
      path: package-output/attendee-service.jar

- name: smoke_test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [deploy]
  - task: smoke_test
    file: attendee-service-source/ci/tasks/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: https://attendee-service-droitural-relaxedness.local.pcfdev.io